const TOGGLE_THEME = "TOGGLE_THEME";
const GET_LIST_JOBS_SUCCESS = "GET_LIST_JOBS_SUCCESS";
const GET_LIST_EMPLOYS_SUCCESS = "GET_LIST_EMPLOYS_SUCCESS";
const GET_TIMES_SUCCESS = "GET_TIMES_SUCCESS";
const GET_AMOUNT_TIMES_SUCCESS = "GET_AMOUNT_TIMES_SUCCESS";
const GET_LIST_LOCATIONS_SUCCESS = "GET_LIST_LOCATIONS_SUCCESS";
const SIGN_IN = "SIGN_IN";
const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS";
const GET_ALL_USER = "GET_ALL_USER";

export {
  GET_LIST_LOCATIONS_SUCCESS,
  GET_AMOUNT_TIMES_SUCCESS,
  TOGGLE_THEME,
  GET_LIST_JOBS_SUCCESS,
  GET_LIST_EMPLOYS_SUCCESS,
  GET_TIMES_SUCCESS,
  SIGN_IN_SUCCESS,
  SIGN_IN,
  GET_ALL_USER,
  GET_ALL_USER_SUCCESS,
};
