const TOGGLE_THEME = "TOGGLE_THEME";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const GET_LIST_QUEUE_SUCCESS = "GET_LIST_QUEUE_SUCCESS";
const CHANGE_CURRENT_QUEUE = "CHANGE_CURRENT_QUEUE";

export {
  TOGGLE_THEME,
  LOGIN_SUCCESS,
  CHANGE_CURRENT_QUEUE,
  GET_LIST_QUEUE_SUCCESS,
};
