const TOGGLE_THEME = "TOGGLE_THEME";
const GET_LIST_JOBS_SUCCESS = "GET_LIST_JOBS_SUCCESS";
const GET_LIST_EMPLOYS_SUCCESS = "GET_LIST_EMPLOYS_SUCCESS";

export { TOGGLE_THEME, GET_LIST_JOBS_SUCCESS, GET_LIST_EMPLOYS_SUCCESS };
